@startuml
left to right direction
skinparam usecase {
  BackgroundColor LightCyan
  BorderColor DarkBlue
}
actor "Zalogowany\nUżytkownik" as ZU
actor "Członek" as M
actor "Admin" as A
actor "Właściciel" as W

W -|> A
A -|> M
M -|> ZU

rectangle "Moduł 3: Zadania i Organizacja" {
  usecase "PU-19: Tworzenie zadania" as PU19
  usecase "PU-20: Status zadania" as PU20
  usecase "PU-21: Przesyłanie wyników" as PU21
  usecase "PU-22: Usuwanie zadania" as PU22
  usecase "PU-24: Powiadomienia" as PU24
  usecase "PU-26: Kalendarz pracy" as PU26
}

ZU --> PU24
M --> PU20
M --> PU21
M --> PU26
A --> PU19
A --> PU22
@enduml